services:
  - type: web
    name: ecosense-hanoi
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # This means you'll set it manually in the Render dashboard
      - key: SESSION_SECRET
        generateValue: true  # Render will generate a random value for this
      # Add other environment variables as needed:
      # - key: API_KEY
      #   sync: false
